Updated with php 8.4
laminas/laminas-xml pull request #19
Opened 2024-10-09 12:13 UTC by SuperDJ

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

- Added PHP 8.4;
- Updated `squizlabs/php_codesniffer` to use the [new repository](https://github.com/PHPCSStandards/PHP_CodeSniffer/);

2024-10-10 11:16 UTC, gsteel requested changes
There are PHP deprecations getting emitted during tests:

https://github.com/laminas/laminas-xml/actions/runs/11254698819/job/31292696978?pr=19#step:3:380

These will need to be fixed _(and PHPUnit should be configured to `failOnDeprecation`)_

There are 4 implicit null arguments by the look of it

2024-10-10 13:21 UTC, SuperDJ commented
@gsteel Unfortunately the optional parameter order is deprecated as well https://github.com/laminas/laminas-xml/actions/runs/11274526733/job/31353887275?pr=19#step:3:231

2024-10-10 13:29 UTC, gsteel requested changes

2024-10-10 13:29 UTC, gsteel commented on src/Security.php
> +    private static function scanString($xml, DOMDocument|null $dom = null, $libXmlConstants, callable $callback)
```suggestion
    private static function scanString($xml, DOMDocument|null $dom, $libXmlConstants, callable $callback)
```

This is a private method - you can do anything you like to it!

2024-10-10 13:29 UTC, gsteel commented on phpunit.xml.dist
> +    failOnDeprecation="true"
At the risk of being a pain in the ass, would you mind adding these too?:

- `failOnWarning`
- `failOnNotice`

2024-10-10 13:32 UTC, gsteel commented on phpunit.xml.dist
> +    failOnDeprecation="true"
Also, these are helpful:

```xml
        displayDetailsOnTestsThatTriggerDeprecations="true"
        displayDetailsOnTestsThatTriggerErrors="true"
        displayDetailsOnTestsThatTriggerNotices="true"
        displayDetailsOnTestsThatTriggerWarnings="true"
```

2024-10-10 16:33 UTC, gsteel requested changes
@SuperDJ If you could trim trailing whitespace in the readme and fix the min PHPunit version, we should have green CI

Thanks for sticking with it!

2024-10-10 16:33 UTC, gsteel commented on composer.json
> +		"phpunit/phpunit": "^10.5 || ^11.4",
Bumping min version of phpunit to 10.5.35 should fix CI failures on 8.4 lowest

2024-10-11 08:45 UTC, gsteel approved these changes
Thanks @SuperDJ - Much appreciated :)

2024-10-11 08:45 UTC, merged